  - label: "Automated Tests"
    plugins:
       - docker-compose#v3.7.0:
          config: .buildkite/docker-compose.yaml
          run: app_read
          environment:
            - SSH_AUTH_SOCK=/ssh-agent.sock
            - REDIS_VALUE=mytestvalue115
          volumes:
            - /run/host-services/ssh-auth.sock:/ssh-agent.sock
            - /var/lib/buildkite-agent/.ssh/known_hosts:/root/.ssh/known_hosts
    agents:
      queue: ykisialiou-dev
    command: .buildkite/redis_test.sh
